const TTH_ISOL = [
  "Foodingredientsfirst",
  "Foodnavigator",
  "Dairyreporter",
  "Beveragedaily",
  "Foodnavigatoreurope",
  "Vegonomist",
  "Worldbakersdossier",
  "Biodiesel",
  "Foodbev",
  "Bakery_snacks",
  "Peformer_Florist",
  "Freshlybottled",
  "Dairyfoods",
  "world_of_foodingredients",
  "BrewingBeverage_Industry_Int",
  "Milling_Baking_News",
  "BakingBusiness",
  "Nutra_ingredients",
  "Nutrition_insight",
  "IDM",
  "Cheese_com",
  "Molkerei_industrie",
  "Food_tech",
  "ILE",
  "Technifood",
  "Maelkeritidende",
  "Process_alimentaire",
  "Perfumer_Flavorist",
  "Newmeat",
  "Food_Business_News",
];

const Human_Nutrition = [
  "nutraingredients",
  "food_navigator",
  "natural_products_insider",
  "nutraceuticals_world",
  "nutritional_outlook",
  "pharmaceutical_technology",
  "vitafoods_insights",
  "nutrition_insight",
  "fierce_pharma",
  "food_news",
  "ingredients_latam",
];

export default { Human_Nutrition, TTH_ISOL };
